### ISSUE TITLE
migration rate estimates

### ISSUE THREAD

**Issue by agladstein** [popgensims/manuscript#105]
I'm pretty sure we talked about this on a call, but I don't remember. 
Why are the estimates for migration rate in humans so far off the truth?
Fig S6.
I don't think this is discussed anywhere in the text.

**Comment by ckyriazis** [comment]
good catch...i dont think we've talked about this (at least not in a while) but tbh I'm really not sure. could be some sort of artefact from the model misspecification.

**Comment by agladstein** [comment]
Or is it a typo?  Is the true EU-AF migration rate really = AF-EU? and why would one direction be good at estimating it, but not the other way?

**Comment by ckyriazis** [comment]
just double checked and it is indeed the same bidirectional migration rate of 3e5 in the simulated model. 

i think it could maybe have something to do with the fact that we do a good job of inferring the pop size of AF but not EU with the IM model, which could maybe impact effective migration rates? just speculation...it would be good to get others (@RyanGutenkunst @andrewkern @klohmueller) to weigh in.

**Comment by RyanGutenkunst** [comment]
Clarification... Typically migration rates are written so m12 is migration into 1 from 2. But the arrows in panel B of the figure suggest otherwise. Which direction is Mig_EU_AF, for example?

**Comment by ckyriazis** [comment]
good catch @RyanGutenkunst. the figure in panel B is in error - I will update that. meaning that the migration directions in the SI figs are as you would expect.

**Comment by RyanGutenkunst** [comment]
Great. Then it makes sense that this is indeed a side-effect of the population size estimation issue and it affects migration into Africa much more strongly than migration into Europe. The net effect of migration is going to depend on the migration rate into the population and drift in that population. Since we get the rate of drift in African correct (due to the correct pop size), we can also get the migration effect (almost) correct. Since we get the rate of drift in Europe wrong (due to incorrect pop size) the migration estimate is biased. Off-hand, I don't have good intuition about why the migration rate into Europe is overestimated. That probably depends on the balance of too-slow versus too-fast drift in Europe, from missing the bottleneck and then the growth.

**Comment by agladstein** [comment]
Can we maybe add a shortened version of this explanation somewhere in the text?

**Comment by ckyriazis** [comment]
thanks for the input @RyanGutenkunst! makes sense. 

also, after talking with kirk just now, we were thinking that this could also be a result of the migration from the CHB population, which essentially functions as a ghost population here. 

i'm not sure how much we want to speculate about this in text, given that we havent really spent much time trying to figure out why exactly we're getting this result. maybe we could just say something hand-wavy about it being an artefact of model misspecification and call it a day?

**Comment by andrewkern** [comment]
I think a couple of sentences along these lines is the max that we would want to add

**Comment by RyanGutenkunst** [comment]
Yep, the ghost population is certainly also a factor. It's hard to judge which effect is more important, pop size or ghost without some detailed study. So yes, let's wave hands vigorously!

**Comment by ckyriazis** [comment]
i took a stab at addressing this this in #114

**Comment by agladstein** [comment]
Looks better to me 😄
