### ISSUE TITLE
census sizes and inverse coal rates

### ISSUE THREAD

**Issue by ckyriazis** [popgensims/manuscript#160]
Reviewer 1 suggested including both census size and inverse coalescence rates in all figures:

> 7. Page 8. I like the approach of showing inverse coalescent rates, but it would be instructive to practitioners and useful for teaching, if in all figures you showed both the census sizes (e.g. with light grey dashed lines) and inverse rates (e.g. with dark grey solid lines as now in Fig 2). 

I'm not if we should do this for a few reasons: 1) some of the figures are already a bit busy when including three inference replicates and one 'truth' line, 2) my understanding is that the inverse coalescence rates are calculated for each population separately to account for migration impacting Ne estimates in the single pop case, but I'm not sure this is as useful in the multi-pop case. What do others think?

Also, on a related topic, reviewer 3 suggested adding a reference on census vs. effective pop sizes for the reader to further explore this issue: 

>  -Page 12, first paragraph: include a reference where people could learn more about the effective population size vs. census size, random-mating models, etc 

I could easily add a reference here (the first paper that comes to mind is Wang et al 2016 Heredity), however I'm not sure if that really helps clarify the issue we're dealing with here (determining what the 'truth' in the presence of model misspecification) and I worry it might confuse the reader. Are there any references people know of that could provide more background on the issue of model misspecification in demographic inference? For reference, here is the passage that is being referred to from the paper:

> For human models with more than two populations (e.g., Gutenkunst et al. (2009)) this means that we are inferring parameters for a model that does not match the model from which the data were generated (Figures 4A and B). However, because the inferred models here better match the simulated models than in the single population case, here we compare our inferred population sizes directly to the census size of the simulated models (black line in Figure 4C).

**Comment by asiepel** [comment]
happy to discuss but my instinct would be to resist an effort to report census size — it’s really messy to characterize the relationship between it and Ne, and any simple attempt is likely to be misleading.  -A

**Comment by petrelharp** [comment]
> any simple attempt is likely to be misleading.

I'm happy either way, but as a counter-point, what people often would like to imagine they are learning about is census size, and while in principle everyone knows these are different, reminders/illustrations of the differences are not a bad thing.  Maybe we could put the census size lines on in an uobtrusive way - dotted, and light-colored?

**Comment by ckyriazis** [comment]
Thanks all for the input. Just to be clear though, by 'census size' here I mean the true effective population sizes that were set our simulations, as opposed to the 'truth' from the ICR (as a reminder, the single pop plots report ICR as the 'truth' and the two pop plots use 'census'). 

Perhaps we could think of a better way of describing it than 'census size' here since that seems to be causing some of the confusion. And although I think the issue of census vs effective pop sizes is an important one, I'm not sure if our results really address that topic in any direct way, so I'm not really sure if discussion of this topic would be warranted.

**Comment by asiepel** [comment]
I see.  That might change my view — I think it’s reasonable to find a way to show the true Ne used in simulation.  But I’d avoid calling it “census size”.    -A

On Apr 8, 2020, at 7:08 PM, ckyriazis <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks all for the input. Just to be clear though, by 'census size' here I mean the true effective population sizes that were set our simulations, as opposed to the 'truth' from the ICR (as a reminder, the single pop plots report ICR as the 'truth' and the two pop plots use 'census').

Perhaps we could think of a better way of describing it than 'census size' here since that seems to be causing some of the confusion. And although I think the issue of census vs effective pop sizes is an important one, I'm not sure if our results really address that topic in any direct way, so I'm not really sure if discussion of this topic would be warranted.

**Comment by petrelharp** [comment]
The consensus on the call today was to
- add census size curves to Figures 2, 3, S1, S2, and S3
- but not Fig 4, because it's less helpful in that context where the model we're fitting has multiple pops
- explain in the caption/text what's there and why it differs, and why it isn't in Fig 4
- say "simulated population size" and/or "population size from the published model" instead of "census size", which is causing confusion.

**Comment by asiepel** [comment]
This sounds good, thanks.

On Apr 14, 2020, at 1:08 PM, Peter Ralph <notifications@github.com<mailto:notifications@github.com>> wrote:



The consensus on the call today was to

  *   add census size curves to Figures 2, 3, S1, S2, and S3
  *   but not Fig 4, because it's less helpful in that context where the model we're fitting has multiple pops
  *   explain in the caption/text what's there and why it differs, and why it isn't in Fig 4
  *   say "simulated population size" and/or "population size from the published model" instead of "census size", which is causing confusion.

**Comment by ckyriazis** [comment]
Took care of this in #171  - this can be closed

**Comment by petrelharp** [comment]
Sorry, this isn't closed - at least on `master` there's no census sizes or mention of it in the figure captions (eg [here](https://github.com/popsim-consortium/manuscript/blob/master/popSimManu.tex#L440) - did you forget to `git add` something, @ckyriazis?

**Comment by ckyriazis** [comment]
ah yea sorry, i meant for @jradrion to revise the captions for these figures with the appropriate description when he adds the updated figures. so this should remain open until that is complete.

**Comment by jradrion** [comment]
After plotting a draft figure, I'd like to question the utility of including lines for the census sizes. Take a look at Figure 2. Here I'm plotting the census population size trajectories in red for higher visibility. For much of the plot the population size trajectories are very difficult to distinguish from the coalescent rate. IMHO, it adds unneeded complexity to the figure.  
![F2](https://user-images.githubusercontent.com/20053488/79913821-144db400-83d9-11ea-97d9-8527fae56c6a.png)

**Comment by jradrion** [comment]
I'm happy to include them if that's what the group would like, but I thought people might like to see the figures first. Also, if we do keep the census lines, we should decide on what color and linetype to use.

**Comment by jradrion** [comment]
I guess if it's plotted as a dotted line the same color as the coalescent rates it doesn't look too bad... I still think it complicates the message without adding much.
![F2B](https://user-images.githubusercontent.com/20053488/79914746-9a1e2f00-83da-11ea-9f46-f023fa5b1856.png)

**Comment by petrelharp** [comment]
Gee, I don't think the red lines get in the way that much. But - are they right? Since there's population splits, the census size for CHB and CEU should switch over to YRI past some point?

**Comment by jradrion** [comment]
> the census size for CHB and CEU should switch over to YRI past some point?

Yeah I was wondering about that. I guess I assumed that the population splits were automatically accounted for, but apparently not because the returned population size for CHB approaches zero as you move back in time using both `population_size_history` and `population_size_trajectory`. 

This might be a silly question but is there a direct way to get the epoch time for a mass migration event? I can get all epoch times with `epoch_times`, and I can see the mass migrations when I `print_history`. I could parse `print_history` to get this information, but maybe I'm overlooking an easier way?

For example, using `print_history` I see
```
Events @ generation 1241.3793103448277
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 2 & dest 1
                     (equivalent to migration from 1 to 2 forwards in time)
```
which means that the census size for population 2 after generation 1241 needs to be taken from population 1 instead, correct?

**Comment by jradrion** [comment]
Also, maybe I'm missing something, but if population size for CHB approaches zero as you move back in time using `population_size_history`, why doesn't CEU do the same? Maybe this is a bug? or am I just totally lost here?

**Comment by petrelharp** [comment]
Well, you can get the mass migrations like so:
```
species = stdpopsim.get_species("HomSap")
model = species.get_demographic_model("OutOfAfricaArchaicAdmixture_5R19")
dd = model.get_demography_debugger()
mm = [x for x in dd.demographic_events if x.type == "mass_migration"]
mm
# [{'type': 'mass_migration', 'time': 1241.3793103448277, 'source': 2, 'dest': 1, 'proportion': 1.0}, {'type': 'mass_migration', 'time': 2093.103448275862, 'source': 1, 'dest': 0, 'proportion': 1.0}, {'type': 'mass_migration', 'time': 17206.896551724138, 'source': 4, 'dest': 0, 'proportion': 1.0}, {'type': 'mass_migration', 'time': 19275.862068965518, 'source': 3, 'dest': 0, 'proportion': 1.0}]
```
so then maybe the code you want is this (after consulting [the MassMigration docs](https://msprime.readthedocs.io/en/stable/api.html#msprime.MassMigration):
```
steps = np.linspace(0, 1e6, 1000)
N = dd.population_size_trajectory(steps)
for m in mm:
    n = (steps > m.time)
    N[n, m.source] = N[n, m.dest]
```

**Comment by petrelharp** [comment]
>  why doesn't CEU do the same? 

Good question; I wondered the same. Looking at `dd.print_history()`, it's all good:
```
=========================================
Epoch: 0 -- 644.8275862068965 generations
=========================================
     start     end      growth_rate |     0        1        2        3        4    
   -------- --------       -------- | -------- -------- -------- -------- -------- 
0 |1.39e+04 1.39e+04              0 |     0    2.48e-05     0        0        0    
1 |1.09e+04 4.85e+03        0.00125 | 2.48e-05     0    0.000113     0        0    
2 |6.58e+04 5.98e+03        0.00372 |     0    0.000113     0        0        0    
...
Events @ generation 1241.3793103448277
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 2 & dest 1
                     (equivalent to migration from 1 to 2 forwards in time)
   - Population parameter change for 1: initial_size -> 880 growth_rate -> 0 
Events @ generation 2093.103448275862
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 1 & dest 0
                     (equivalent to migration from 0 to 1 forwards in time)
```
Since [YRI=0, CEU=1, CHB=2](https://stdpopsim.readthedocs.io/en/latest/catalog.html#sec_catalog_homsap_models_outofafricaarchaicadmixture_5r19), this says that both CEU and CHB start with positive growth rate; then CHB merges with CEU and the growth rate in that population (which is still labeled 1, so is CEU) is set to zero; then this one (CEU) merges with YRI.

**Comment by ckyriazis** [comment]
I think these look nice @jradrion! Though I agree they do make the plots a bit busy, I think its informative to see the areas where IRC differs from census for thinking about what happens when you have model misspecification. I dont think these issues would be immediately obvious to a good portion of our readership, so I think its worth including to really drive the point home. Also, its an easy thing to do to make reviewer 1 happy since we're not doing many of their other suggestions. 

One minor issue: would it be possible to have the census sizes in the solid black for consistency with the two pop figs? I think it could be a bit confusing otherwise.

**Comment by jradrion** [comment]
> Well, you can get the mass migrations like so:

Ahh, yes, this was basically what I was looking for. Sorry, I should have just spent a bit more time with the docs. Thanks, @petrelharp !

> would it be possible to have the census sizes in the solid black for consistency with the two pop figs?

@ckyriazis How's this? Not much difference between census and IRC...

![F2C](https://user-images.githubusercontent.com/20053488/80017603-b4fbac80-8489-11ea-93e6-23dfeb3df814.png)

**Comment by jradrion** [comment]
How do people feel about slightly larger font sizes and line weights? I think something like this looks a bit better...though it might require updates for the multi-pop figures for consistency.
![F2D](https://user-images.githubusercontent.com/20053488/80019126-e4131d80-848b-11ea-9958-de3df2157646.png)

**Comment by ckyriazis** [comment]
mmm yea you're right...very similar after taking care of the issue above. i'm torn. what do others think?

to be clear, if we do keep census, i was thinking not only change it to match the two pop figs (where i guess census is actually in that slate color) but also make the IRC color different so its easier to distinguish.

the larger font sizes and lines look good! i can definitely update the other figs for consistency.

**Comment by grahamgower** [comment]
Absolutely, bigger font sizes are a win. I find it hard to distinguish the black and gray lines though.

And the different alignment of "SMC++" from the other titles bothers my OCD. :) Maybe the SMC++ and stairway plot columns could be switched, so the lower-case "stairway plot" is misaligned instead?

**Comment by jradrion** [comment]
OK, so I think better colors to differentiate census from IRC is a must.

> And the different alignment of "SMC++" from the other titles bothers my OCD. :) Maybe the SMC++ and stairway plot columns could be switched, so the lower-case "stairway plot" is misaligned instead?

I might just align those in illustrator, but I agree, it's a bit bothersome.

**Comment by jradrion** [comment]
What do people think about adding a legend vs simply describing the lines in the caption?

**Comment by jradrion** [comment]
> And the different alignment of "SMC++" from the other titles bothers my OCD. :) Maybe the SMC++ and stairway plot columns could be switched, so the lower-case "stairway plot" is misaligned instead?

actually looking more closely, the alignment issue is actually due the the plots in the first column having a title. If you look close you can see that the top of the y-axis is not aligned either between column 1 and the rest. I think I'll dump those titles and add them in illustrator (or maybe cowplot) too.

**Comment by petrelharp** [comment]
Ah, nice!

Hm, they're so similar that I think it will be confusing having them in the same figure - like, people will read "census sizes are shown in red" and think "what red line?" What if we put just one line on this figure (either one) and then put a version of the plot with both lines, or maybe even just the plot with inverse coal rate and census size, in the supplement?

**Comment by jradrion** [comment]
@petrelharp I like the idea of only showing one or the other in the main plot, with a supplemental plot showing an example or two of census vs IRC.

**Comment by petrelharp** [comment]
Can you make that figure also?

**Comment by gphocs-dev** [comment]
I know I'm a bit late to join the discussion. Personally, I think that the version with both measures looks fine. However, if people think that having two nearly identical measures reflecting the "true Ne", then I think that we should show the simulated Ne and drop IRC. IRC is a really neat concept and useful in some cases, but if it doesn't actually depart from the simulated Ne, then it's not very informative (as is the case apparently in figs 2-3). I think that we can show both to highlight that in this specific case we can actually hope to infer the simulated Ne. However, in other models that might not be the case, and the IRC represents the best approximation of the simulated Ne that we can hope to infer. I also agree that in the multi-pop analyses it's not very relevant, because the demography inference methods we use there allow for gene flow.
