### ISSUE TITLE
add details of melanogaster two population run times / failures

### ISSUE THREAD

**Issue by andrewkern** [popgensims/manuscript#27]
hey @jradrion - can you add a couple of sentences at this point in the manuscript describing your efforts to get two population fly simulations for the whole genome?
https://github.com/popgensims/manuscript/blob/94e3838215a1a3c1e8beaf867724079597429fb4/popSimManu.tex#L536

**Comment by jradrion** [comment]
No problem @andrewkern . However, I'm happy to report that the independent runs of chromosomes 2L, 2R, and 3L have actually finished running! Chr 3R and chr X are still running (19 days so far) so perhaps I should just wait for them to finish so I can include all the runtimes, etc? Presumably they should be finishing up soonish, although recombination rates on the X are significantly higher than on the autosomes, so that may take longer still.

I can pass the completed .ts files to @ckyriazis for the 2pop analysis so we can include the results in the draft.

**Comment by andrewkern** [comment]
wow that's great!

**Comment by jeromekelleher** [comment]
I think you can make a claim for the longest running msprime simulation record @jradrion! How big are the tree sequence files out of interest?

**Comment by jradrion** [comment]
@andrewkern yeah, it was about time!

@jeromekelleher Ha, yes perhaps!

The files are on the order of 3-4 GB per chromosome.

**Comment by jeromekelleher** [comment]
> The files are on the order of 3-4 GB per chromosome.

Jeez, that's a BIG tree sequence! Can we make these available for download somewhere? These'll be great for benchmarking tree sequence algorithms.

**Comment by jradrion** [comment]
Yes, I should have mentioned that they can be found [here](http://sesame.uoregon.edu/~jadrion/).

I will populate this directory with the remaining chromosomes whenever they finish.

**Comment by ckyriazis** [comment]
awesome @jradrion! i'll be ready to rerun the analysis pipeline when they all finish

**Comment by ckyriazis** [comment]
Hey @jradrion are these still running?

**Comment by jradrion** [comment]
@ckyriazis Yes, they are still running. However, they will be killed tomorrow morning due to routine server maintenance. It's still possible that chr3R will finish by then, and if it does I will transfer the results to my public html directory and notify you. I don't think there is hope for the X finishing by then. I went ahead and started simulations for 3 reps of the X on Andy's personal server, which is not subject to a maintenance schedule. I'll do the same for 3R if the current sims don't finish in time. We're looking at an additional >30 days for those, so we should plan around them for the first draft.

**Comment by ckyriazis** [comment]
Thanks for the update @jradrion! Fingers crossed that 3R finishes by tomorrow. 

Quick question for chrX: would we want to even use this for inference? Would it not result in downward biases in the inferred Ne?

**Comment by jradrion** [comment]
`Quick question for chrX: would we want to even use this for inference? Would it not result in downward biases in the inferred Ne?`

My intention in running chrX was for the sake of completeness. IIRC, expected heterozygosity is not dramatically different between the X and autosomes in some Drosophila populations.

**Comment by jradrion** [comment]
Update: Chromosomes 3R and X did not finish in time. Both of these chromosomes are now being rerun on Andy's server and will take at least 30 days to finish.

I'm going to add detail about the completed simulations to the methods section today.

**Comment by jeromekelleher** [comment]
So, given that these ended up being invalid  simulations due to a bug in msprime, is there much point in talking about them?

**Comment by andrewkern** [comment]
probably not...

**Comment by agladstein** [comment]
So, I was confused by the paragraph https://github.com/popsim-consortium/manuscript/blob/master/popSimManu.tex#L773

I think the whole discussion of run times and why some of the chromosomes can be left out. Otherwise, if you leave it in, it should have some explanation of why it took so long. As it is, as a reader, I would confused as to why it doesn't line up with the table. Everything looks awesome in the table and makes me want to use it, but then you say it ran for 30 days and couldn't finish. That sounds bad, and the specific case should be explained so I can have an expectation if I'll encounter that too.

**Comment by ckyriazis** [comment]
hmmm yea good point @agladstein, I see how that can be confusing. as far as i understand, I think the discrepancy between the table and these results is the fact we used a map rather than uniform recomb rates, which made it super slow. should we maybe mention that in the text? pinging @andrewkern and @jradrion for input.

**Comment by agladstein** [comment]
@ckyriazis I would suspect so. And I asked @jeromekelleher about adding recomb map to table, but he argued against, which is fine. But, without explanation, it's kinda confusing because it doesn't line up.

**Comment by agladstein** [comment]
I think the commit https://github.com/popsim-consortium/manuscript/commit/4c5c4d454f378c20dab1ca0342c97441fae63297 from @ckyriazis improves that paragraph. 
Maybe one additional line that's says something about using the recombination map?

**Comment by ckyriazis** [comment]
yea thats what i was thinking. ill take a stab at that.

**Comment by ckyriazis** [comment]
i tried to address this with #114

**Comment by agladstein** [comment]
I think that looks better now.

**Comment by andrewkern** [comment]
yes closing. this is done.
